@TodoApp.Api_HostAddress = http://localhost:5181

POST {{TodoApp.Api_HostAddress}}/user/create
Content-Type: application/json

{
  "Username": "Person6",
  "Password": "Test"
}

###
POST {{TodoApp.Api_HostAddress}}/auth/login
Content-Type: application/json

{
  "Username": "Person",
  "Password": "Test"
}

###
GET {{TodoApp.Api_HostAddress}}/auth/renew-token

###
GET {{TodoApp.Api_HostAddress}}/item/all
Authorization: Bearer 

###
POST {{TodoApp.Api_HostAddress}}/item/create
Content-Type: application/json
Authorization: Bearer 

{
  "Name": "Test Item 2",
  "Description": "Test desc 2",
  "Completed": true
}

###