@TodoApp.Api_HostAddress = http://localhost:5181

POST {{TodoApp.Api_HostAddress}}/user/create
Content-Type: application/json

{
  "Username": "Person",
  "Password": "Test"
}

###
POST {{TodoApp.Api_HostAddress}}/auth/login
Content-Type: application/json

{
  "Username": "Person",
  "Password": "Test"
}

###
